server:
  port: 3031
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    listener:
      missing-topics-fatal: false
      ack-mode: RECORD
    consumer:
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      group-id: store_order_id, store_payment_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        allow.auto.create.topics: true
        spring.json.trusted.packages: "com.fawry.kafka.events"
        spring.json.type.mapping: orderCreatedEventDTO:com.fawry.kafka.events.OrderCreatedEventDTO, orderCanceledEventDTO:com.fawry.kafka.events.OrderCanceledEventDTO

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: